trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: 'Build Website'

  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: ArchiveFiles@2
      displayName: 'Archive Website'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/website.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'website'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build

  jobs:
  - deployment: DeployWebsite
    displayName: 'Deploy Website'
    environment: 'Production'

    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: website

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: '1805b92d-4c00-48f9-becf-9b43175fcb91'
              appType: 'webAppLinux'
              appName: 'javakiapplication'
              package: '$(Pipeline.Workspace)/website/website.zip'